<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c1b9d8c2-9b2e-46e7-a5d0-33489b20b6e0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ForgeScheduler.Application\ForgeScheduler.Application.csproj" />
    <ProjectReference Include="..\ForgeScheduler.Domain\ForgeScheduler.Domain.csproj" />
    <ProjectReference Include="..\ForgeScheduler.Infrastructure\ForgeScheduler.Infrastructure.csproj" />
  </ItemGroup>

</Project>
