<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ForgeScheduler.Worker-f5c20823-89e6-4a89-a8fe-d5418fe8353d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ForgeScheduler.Application\ForgeScheduler.Application.csproj" />
    <ProjectReference Include="..\ForgeScheduler.Infrastructure\ForgeScheduler.Infrastructure.csproj" />
  </ItemGroup>
</Project>
